name: CI

on:
  push:
    branches:
      - feature/build
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd todo_site/
        ls -la

    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4.3.0
      with:
        # Docker CE version. (e.g, v24.0.9)
        version: v24.0.9

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}


    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:todo_site"
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/flask-app:${{ github.event.inputs.tag || 'latest' }}
        